services:
  web:
    build: .
    ports:
      - "5000:80"
    volumes:
      - .:/app1
    depends_on:
      - db
      - redis
    env_file:
      - ./.env
  worker:
    build: .
    volumes:
      - .:/app1
    env_file:
      - ./.env
    depends_on:
      - redis
      - db
    command: >
      sh -c "
      if [ ! -d /app1/.venv ]; then
        python -m venv /app1/.venv &&
        /app1/.venv/bin/pip install -r /app1/requirements.txt;
      fi &&
      /app1/.venv/bin/rq worker emails
      "

  db:
    image: postgres:18
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=app1
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
volumes:
  postgres_data:      